/*
 * test_printer.mjs — verifies the JavaScript printer-protocol port against
 * the Python reference implementation (ptcbp.py, labelmaker_encode.py,
 * ptstatus.py).
 *
 * Run:  node web/test_printer.mjs
 *
 * The test loads printer.js with a minimal `window` shim, then compares the
 * produced byte streams with golden values generated by the Python code.
 */

import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import vm from 'node:vm';

const __dirname = dirname(fileURLToPath(import.meta.url));

// --- Load printer.js with a window shim -----------------------------------
const src = readFileSync(join(__dirname, 'printer.js'), 'utf8');
const sandbox = { window: {}, console, Uint8Array, ArrayBuffer, DataView, Math, Date, Promise, setTimeout };
vm.createContext(sandbox);
vm.runInContext(src, sandbox);
const P = sandbox.window.PTPrinter;

// --- Tiny test framework ---------------------------------------------------
let passed = 0, failed = 0;
function eq(actual, expected, msg) {
  const a = JSON.stringify(actual);
  const e = JSON.stringify(expected);
  if (a === e) { passed++; console.log(`  ok   ${msg}`); }
  else { failed++; console.log(`  FAIL ${msg}\n       expected ${e}\n       actual   ${a}`); }
}
function hex(bytes) {
  return Array.from(bytes).map((b) => b.toString(16).padStart(2, '0')).join('');
}

// --- ptcbp.serialize_control ----------------------------------------------
console.log('ptcbp.serialize_control');
eq(hex(P.serializeControl('reset')), '1b40', 'reset');
eq(hex(P.serializeControl('get_status')), '1b6953', 'get_status');
eq(hex(P.serializeControl('use_command_set', 1)), '1b696101', 'use_command_set ptcbp');
eq(hex(P.serializeControl('set_page_mode', 0)), '1b694d00', 'set_page_mode 0');
eq(hex(P.serializeControl('set_page_mode_advanced', 8)), '1b694b08', 'set_page_mode_advanced 8');
eq(hex(P.serializeControl('set_page_margin', 0)), '1b69640000', 'set_page_margin 0');
eq(hex(P.serializeControl('compression', 2)), '4d02', 'compression rle');
eq(hex(P.serializeControl('print')), '1a', 'print');
eq(hex(P.serializeControl('zerofill')), '5a', 'zerofill');

// set_print_parameters: '4BI2B' = B,B,B,B,I,B,B
// active_fields = width|quality|recovery = 4|64|128 = 196
eq(hex(P.serializeControl('set_print_parameters', 196, 1, 12, 0, 16, 0, 0)),
   '1b697ac4010c00100000000000', 'set_print_parameters');

// --- packbits RLE ----------------------------------------------------------
console.log('packbitsEncode');
// A run of 5 identical bytes -> header 257-5=252 (0xfc), then the byte.
eq(hex(P.packbitsEncode(new Uint8Array([0, 0, 0, 0, 0]))), 'fc00', 'run of 5 zeros');
// Literal run of 3 distinct bytes -> header 2, then the bytes.
eq(hex(P.packbitsEncode(new Uint8Array([1, 2, 3]))), '02010203', 'literal 1,2,3');
// Mixed: 2 identical then 3 distinct.
eq(hex(P.packbitsEncode(new Uint8Array([9, 9, 1, 2, 3]))), 'ff0902010203', 'run+literal');

// --- serialize_data --------------------------------------------------------
console.log('serializeData');
// data opcode 'G' (0x47) + length (LE uint16) + payload.
eq(hex(P.serializeData(new Uint8Array([1, 2, 3]), 'none')), '470300010203', 'data none');
eq(hex(P.serializeData(new Uint8Array([0, 0, 0, 0, 0]), 'rle')), '470200fc00', 'data rle');

// --- encode_raster_transfer ------------------------------------------------
console.log('encodeRasterTransfer');
{
  // One zero line (16 bytes) -> zerofill; one non-zero line -> data.
  const data = new Uint8Array(32);
  data[16] = 0xff;
  const lines = [...P.encodeRasterTransfer(data, false)];
  eq(lines.length, 2, 'two chunks');
  eq(hex(lines[0]), '5a', 'first chunk zerofill');
  eq(lines[1][0], 0x47, 'second chunk data opcode');
}

// --- ptstatus.unpack_status ------------------------------------------------
console.log('unpackStatus');
{
  const frame = new Uint8Array(32);
  frame.set([0x80, 0x20, 0x42, 0x30], 0); // magic
  frame[4] = 0x72;                        // model PT-P300BT
  frame[8] = 0x08; frame[9] = 0x00;       // err = 0x0800 (low battery)
  frame[10] = 12; frame[11] = 1;          // tape width/type
  frame[18] = 0x02;                       // status_type error
  frame[19] = 0x01;                       // phase_type
  frame[26] = 0x01; frame[27] = 0x02; frame[28] = 0x03; frame[29] = 0x04;
  const st = P.unpackStatus(frame);
  eq(st.model, 0x72, 'model');
  eq(st.err, 0x0800, 'err');
  eq(st.tape_width, 12, 'tape_width');
  eq(st.status_type, 0x02, 'status_type');
  eq(st.hw_settings, 0x01020304, 'hw_settings big-endian');
  const lines = P.printStatusLines(st);
  eq(lines.some((l) => l.includes('Low battery')), true, 'describes low battery');
  eq(lines.some((l) => l.includes('PT-P300BT')), true, 'describes model');
}

// --- configure_printer_bytes ----------------------------------------------
console.log('configurePrinterBytes');
{
  const parts = P.configurePrinterBytes(16, [1, 12, 0], {
    chaining: false, autoCut: false, endMargin: 0, compress: true,
  });
  // 64-byte flush + reset + use_command_set + set_print_parameters +
  // set_page_mode_advanced + set_page_mode + set_page_margin + compression
  eq(parts.length, 8, 'eight commands');
  eq(parts[0].length, 64, 'flush buffer 64 bytes');
  eq(hex(parts[1]), '1b40', 'reset');
  eq(hex(parts[2]), '1b696101', 'use_command_set');
  eq(parts[3][0], 0x1b, 'set_print_parameters opcode');
  eq(hex(parts[4]), '1b694b08', 'no_page_chaining');
  eq(hex(parts[5]), '1b694d00', 'page mode');
  eq(hex(parts[6]), '1b69640000', 'margin');
  eq(hex(parts[7]), '4d02', 'compression rle');
}

// --- do_print_job end-to-end (fake transport) ------------------------------
console.log('doPrintJob (fake transport)');
{
  function mkStatus(type) {
    const s = new Uint8Array(32);
    s.set([0x80, 0x20, 0x42, 0x30], 0); // magic
    s[18] = type;                        // status_type
    s[19] = 0x00;                        // phase_type = ready
    return s;
  }
  const written = [];
  let reads = 0;
  const fake = {
    async write(b) { written.push(b.slice()); },
    async read() { reads++; return reads === 1 ? mkStatus(0x00) : mkStatus(0x01); },
    async resetInputBuffer() {},
  };
  const data = new Uint8Array(32); // two raster lines
  data[16] = 0xff;
  const logs = [];
  await P.doPrintJob(fake, { nocomp: false, no_feed: false, auto_cut: false, end_margin: 0 },
    data, (l) => logs.push(l), () => {});
  eq(written.length > 0, true, 'wrote commands');
  eq(logs.some((l) => l.includes('Querying printer status')), true, 'logged status query');
  eq(logs.some((l) => l.includes('Configuring printer')), true, 'logged configuration');
  // The final write must be the print command (0x1a).
  const last = written[written.length - 1];
  eq(last[last.length - 1], 0x1a, 'last byte is print (0x1a)');
}

// --- wait_for_print_completion --------------------------------------------
console.log('waitForPrintCompletion');
{
  function mkStatus(type) {
    const s = new Uint8Array(32);
    s.set([0x80, 0x20, 0x42, 0x30], 0);
    s[18] = type;
    return s;
  }
  let reads = 0;
  const fake = {
    async read() { reads++; return reads === 1 ? mkStatus(0x00) : mkStatus(0x01); },
  };
  let threw = false;
  try { await P.waitForPrintCompletion(fake, 5, () => {}); } catch { threw = true; }
  eq(threw, false, 'completes when status_type 0x01 arrives');

  // Error status must throw.
  const errFake = { async read() { const s = mkStatus(0x02); s[8] = 0x08; return s; } };
  let threw2 = false;
  try { await P.waitForPrintCompletion(errFake, 5, () => {}); } catch { threw2 = true; }
  eq(threw2, true, 'throws on error status');
}

// --- Summary ---------------------------------------------------------------
console.log(`\n${passed} passed, ${failed} failed`);
process.exit(failed ? 1 : 0);
